-- Enable RLS on all business tables (no policies = deny for anon/authenticated JWT;
-- service_role bypasses RLS as the postgres role supabase_admin uses for API routes).

ALTER TABLE IF EXISTS public.kategori_barang ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.subkategori_barang ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.satuan_barang ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.spesifikasi_cepat_barang ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.barang ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.harga_barang_satuan ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.opsi_finishing ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pelanggan ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.vendor ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.profil ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.kredensial ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.penjualan ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.item_penjualan ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pembelian ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.item_pembelian ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.piutang_penjualan ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pelunasan_piutang ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hutang_pembelian ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pelunasan_hutang ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.order_produksi ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.item_produksi ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.item_finishing ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.keuangan ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.sync_conflicts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sync_mutation_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.device_registry ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.finance_category_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.finance_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.finance_metric_mappings ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.fiscal_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.chart_of_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.accounting_posting_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.journal_entry_lines ENABLE ROW LEVEL SECURITY;
